### ISSUE TITLE
Packaging confusion between pkgrel and pkgver

### ISSUE THREAD

**Issue by micwoj92** [tfkhdyt/axu#2]
I see that tags on this repo have (what it seems to be) $pkgrel used in the AUR package.
https://github.com/tfkhdyt/axu/tags
$pkgver in package should be used for upstream releases and $pkgrel should be used for PKGBUILD changes
https://wiki.archlinux.org/title/PKGBUILD#pkgrel

I've tried to reupload the axu package to have source build, but I found it confusing on how to implement in correctly, so this request is to stop using "pkgrels" in tags on this repo.

**Comment by tfkhdyt** [comment]
I added "pkgrel" to the tag so that GitHub Actions would automatically release this package to AUR. But now I've fixed this issue. Thanks for your contribution, btw.

https://github.com/tfkhdyt/axu/releases/tag/v1.5.3

**Comment by micwoj92** [comment]
Thanks, I've uploaded the package as build from source.
https://aur.archlinux.org/packages/axu
