### ISSUE TITLE
Doesn't output any packages

### ISSUE THREAD

**Issue by promitheas17j** [tfkhdyt/axu#3]
Whatever way I run it there are no packages output. Obviously I have many explicitly installed packages that it should find and list.

![2023-11-29_04-59](https://github.com/tfkhdyt/axu/assets/12212713/17a07c84-f089-4640-ac78-30c4ec601b7c)

Is it something on my end or a bug?

**Comment by tfkhdyt** [comment]
Try run these commands, and show me the output:
- `checkupdates`
- `yay -Qua`

**Comment by promitheas17j** [comment]
I updated my system, ran both commands, and both returned nothing as output.

Running ```axu``` still gives me
```
Total updates: 0
```

![2023-12-01_00-38](https://github.com/tfkhdyt/axu/assets/12212713/5fa6cc59-a8f0-49b2-b110-275a02f45ecc)

**Comment by tfkhdyt** [comment]
So you run those commands after each system update?

**Comment by promitheas17j** [comment]
Not after each system update. I update between every 1 and 3 days. I mean that I ran them now that you asked for them.

**Comment by tfkhdyt** [comment]
So it's still show no output?

**Comment by promitheas17j** [comment]
Axu show output, but its not what I expect. The output is ```Total updates: 0```.

**Comment by tfkhdyt** [comment]
Fixed https://github.com/tfkhdyt/axu/commit/1e06f43dc5d1a1e5d80020fce856c0b37bcdf316
